print ("=============Biodata===============")
nama = input ('Masukkan nama: ')
alamat = input ('Masukkan alamat: ')
notelp = input ('Masukkan nomor telepon: ')
umur = input ('Masukkan umur: ')
tinggi = input ('Masukkan tinggi: ')
hobi = input ('Masukkan hobi: ')
print ("===================================")
print ('Nama = ' ,nama)
print ('Alamat = ' ,alamat)
print ('No Telp = ',notelp)
print ('Umur = ',umur)
print ('Tinggi = ',tinggi)
print ('Hobi = ',hobi)
print ("=====Data Berhasil Ditambahkan=====")

